language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

scripts: "./gradlew clean build"

before_deploy:
  - zip -r web-sample *
  - mkdir -p deploy
  - mv web-sample.zip deploy/web-sample.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: web-sample-aws-build # S3 Bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings Environment Variable
    secret_access_key: $AWS_SECRET_KEY # Travis repo Environment Variable
    bucket: web-sample-aws-build
    key: web-sample.zip
    bundle_type: zip # extension
    application: web-sample-aws # 웹 콘솔에서 등록한 CodeDeploy Application
    deployment_group: web-sample-aws-group # group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 107micro@gmail.com
