version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permission:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # Nginx와 연결되지 않은 기존 SpringBoot 어플리케이션 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 새 버전의 SpringBoot 어플리케이션 실행
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 시작된 어플리케이션 정상 실행 여부 확인
      timeout: 60
      runas: ec2-user
